#!/usr/bin/env python3
"""Build the trainer at /read/ on paleography.app.

⚑ There used to be TWO builds and the difference bit hard: make_trainer.py produced a
self-contained page for the claude.ai Artifact runtime (no doctype, no head -- the
runtime supplied them), and this script wrapped the same shell for the web. Serving the
Artifact build raw meant quirks mode and no viewport, which shipped once.

The Artifact build is RETIRED (2026-08-28, Wilson's call). The site is canonical, there
is one build, and the trap is gone. This script now goes straight from
tools/trainer_shell.html to site/read/index.html.

Retiring it is also what lets the payload be split: an Artifact can fetch nothing, so
the whole 10.9 MB bank had to be inlined. Now only the ~2 KB index is inlined and each
track's lines are fetched when that track is opened.

The apex (site/index.html) is hand-written and tracked in git -- this script does NOT
write it. Clean per-track URLs are rewrites in site/vercel.json, generated by
tools/make_routes.py.
"""
import json, shutil
from pathlib import Path

root = Path(__file__).resolve().parent.parent
shell = (root / "tools/trainer_shell.html").read_text(encoding="utf-8")
payload_dir = root / "build/payload"
index = (payload_dir / "index.json").read_text(encoding="utf-8")

if "</script" in index.lower():
    raise SystemExit("index contains </script and would break out of the tag")

HEAD = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Learn to read __LANGS__ manuscripts from the images themselves — staged from orientation to full transcription.">
<meta name="color-scheme" content="light dark">
<meta property="og:title" content="Paleography">
<meta property="og:description" content="A staged introduction to reading medieval and ancient manuscripts, built on open ground truth.">
<meta property="og:type" content="website">
<meta property="og:url" content="https://paleography.app/read/">
<meta property="og:image" content="https://paleography.app/og.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="A line of a 13th-century French manuscript above its transcription: Qi ait per-du si ait perdu, the same word written once abbreviated and once in full.">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'><text y='.9em' font-size='56'>%E2%9C%92%EF%B8%8F</text></svg>">
"""
# Vercel Web Analytics, static-site install. NOT the npm package: there is no build step
# and no React here for an <Analytics/> component to hang on. See research/deploy.md.
FOOT = '\n<script defer src="/_vercel/insights/script.js"></script>\n</body>\n</html>\n'

out_dir = root / "site/read"
out_dir.mkdir(parents=True, exist_ok=True)

# the shell opens with <title> and its font links; those belong in <head>, the rest in <body>
marker = '<div class="wrap">'
i = shell.index(marker)
head_part, body_part = shell[:i], shell[i:]
doc = HEAD + head_part + "</head>\n<body>\n" + body_part + FOOT
# The language list is registry data; naming it by hand here is how the old description
# came to say "Greek and Latin" on the day Old French shipped.
import json as _json
_langs = _json.loads(index)["languages"]
_names = [l["name"] for l in _langs.values()]
_phrase = (", ".join(_names[:-1]) + " and " + _names[-1]) if len(_names) > 1 else _names[0]
doc = doc.replace("__LANGS__", _phrase)
doc = doc.replace("__PAYLOAD__", index)

dest = out_dir / "index.html"
dest.write_text(doc, encoding="utf-8")
print(f"{dest} — {dest.stat().st_size/1024:.1f} KB  (index inlined)")

# Stale track files are worse than missing ones: a renamed or retired track would keep
# serving its old bank forever. Clear them, then copy what this build produced.
for old in out_dir.glob("t-*.json"):
    old.unlink()
total = 0
for f in sorted(payload_dir.glob("t-*.json")):
    shutil.copy2(f, out_dir / f.name)
    total += f.stat().st_size
    print(f"  {f.name}  {f.stat().st_size/1024/1024:.2f} MB")
print(f"  {total/1024/1024:.2f} MB of tracks, fetched on demand")
